QB = {}

QB.WelcomeText = "欢迎来到 NEWDAYRP 西部拓荒角色扮演中文社区"

QB.Texts = {
    Body = "身体",
Face = "脸部",
Hair_beard = "发型和胡须",
HairStyle = "发型",
HairColor = "发色",
BeardStyle = "胡须风格",
BeardColor = "胡须颜色",
Makeup = "化妆",
Appearance = "外貌",
Slim = "苗条",
Sporty = "运动型",
Medium = "中等",
Fat = "胖",
Strong = "强壮",
FaceWidth = "脸宽",
SkinTone = "肤色",
Eyes = "眼睛",
Eyelids = "眼睑",
Eyebrows = "眉毛",
Nose = "鼻子",
Mouth = "嘴巴",
Teeth = "牙齿",
Cheekbones = "颧骨",
Jaw = "下巴",
Ears = "耳朵",
Chin = "下巴",
Defects = "瑕疵",
Hair = "头发",
Beard = "胡须",
Type = "类型",
Visibility = "可见性",
ColorPalette = "调色板",
ColorFirstrate = "一级颜色",
Eyebrow = "眉毛",
NoseCurvature = "鼻部曲线",
UP_DOWN = "上下",
left_right = "左右",
UpperLipHeight = "上唇高度",
UpperLipWidth = "上唇宽度",
UpperLipDepth = "上唇深度",
LowerLipHeight = "下唇高度",
LowerLipWidth = "下唇宽度",
LowerLipDepth = "下唇深度",
Make_up = "化妆",
Older = "年长",
Scars = "疤痕类型",
Freckles = "雀斑类型",
Moles = "痣",
Disadvantages = "缺陷",
Spots = "斑点",
Shadow = "阴影",
ColorShadow = "阴影颜色",
ColorFirst_Class = "一级颜色幻觉",
Blushing_Cheek = "脸颊红晕",
blush_id = "脸颊红晕颜色",
blush_c1 = "一级颜色脸颊红晕",
Lipstick = "口红类型",
ColorLipstick = "口红颜色",
lipsticks_c1 = "一级颜色口红",
lipsticks_c2 = "二级颜色口红",
Eyeliners = "眼线",
eyeliners_id = "眼线颜色",
eyeliners_c1 = "一级颜色眼线",
save = "保存",
Options = "选项",
align = "左上角",
Style = "样式",
Color = "颜色",
Size = "尺寸",
Width = "宽度",
Height = "高度",
Depth = "深度",
Waist = "腰部",
Chest = "胸部",
Distance = "距离",
Angle = "角度",
Clarity = "清晰度",
    Color1 = "<img src='nui://qb-appearance/img/skin1.png' height='20'>",
    Color2 = "<img src='nui://qb-appearance/img/skin2.png' height='20'>",
    Color3 = "<img src='nui://qb-appearance/img/skin3.png' height='20'>",
    Color4 = "<img src='nui://qb-appearance/img/skin4.png' height='20'>",
    Color5 = "<img src='nui://qb-appearance/img/skin5.png' height='20'>",
    Color6 = "<img src='nui://qb-appearance/img/skin6.png' height='20'>",
}
