Config = {}

-- settings
Config.SpawnDistanceRadius = 30 -- the distance the animal spawns away from the bait 
Config.HideTime = 10000 -- the amount of time in miliseconds that you have to hide before animal aproaches the bait
Config.AnimalWait = 10000 -- the amount of time in miliseconds that the animal will wait at the bait until freeroam

Config.HuntingZones = {
	{
		name       = 'huntingzone1',
		coords     = vector3(-1054.0793, -673.3105, 72.3116),
		radius     = 100.0, 
		showblip   = false,
        blipName   = 'Hunting Zone',
        blipSprite = `blip_mp_deliver_target`,
        blipScale  = 0.2,
		animal       = 'mp_a_c_boar_01',
		bait       = 'wheat',
		animalname       = 'Boar',
		baitname       = 'wheat',
		enterzone = true,
		health     = 1000.0,
		timer     = 60,
	},
	{
		name       = 'huntingzone2',
		coords     = vector3(-2297.2400, -462.6606, 143.1794),
		radius     = 100.0, 
		showblip   = false,
        blipName   = 'Hunting Zone',
        blipSprite = `blip_mp_deliver_target`,
        blipScale  = 0.2,
		animal     = 'mp_a_c_beaver_01',
		bait       = 'wheat',
		animalname  = 'Beaver',
		baitname    = 'Wheat',
		enterzone = true,
		health     = 1000.0,
		timer     = 60,
	},
	{
		name       = 'huntingzone3',
		coords     = vector3(1191.3398, 2047.3147, 324.7537),
		radius     = 100.0, 
		showblip   = false,
        blipName   = 'Hunting Zone',
        blipSprite = `blip_mp_deliver_target`,
        blipScale  = 0.2,
		animal       = 'mp_a_c_cougar_01',
		bait       = 'gmeat',
		animalname   = 'Cougar',
		baitname       = 'Game Meat',
		enterzone = true,
		health     = 1000.0,
		timer     = 60,
	},
	{
		name       = 'huntingzone4',
		coords     = vector3(-1361.0551, -1384.6249, 94.1296),
		radius     = 100.0, 
		showblip   = false,
        blipName   = 'Hunting Zone6',
        blipSprite = `blip_mp_deliver_target`,
        blipScale  = 0.2,
		animal       = 'mp_a_c_coyote_01',
		bait       = 'gmeat',
		animalname       = 'Coyote',
		baitname       = 'Game Meat',
		enterzone = true,
		health     = 1000.0,
		timer     = 60,
	},
	{
		name       = 'huntingzone5',
		coords     = vector3(390.9921, 1276.2581, 196.6426),
		radius     = 100.0, 
		showblip   = false,
        blipName   = 'Hunting Zone',
        blipSprite = `blip_mp_deliver_target`,
        blipScale  = 0.2,
		animal       = 'mp_a_c_panther_01',
		bait       = 'gmeat',
		animalname       = 'Panther',
		baitname       = 'Game Meat',
		enterzone = true,
		health     = 1000.0,
		timer     = 60,
	},
	{
		name       = 'huntingzone6',
		coords     = vector3(-1392.3319, 2242.6992, 307.9457),
		radius     = 100.0, 
		showblip   = false,
        blipName   = 'Hunting Zone',
        blipSprite = `blip_mp_deliver_target`,
        blipScale  = 0.2,
		animal     = 'mp_a_c_wolf_01',
		bait       = 'birdmeat',
		animalname     = 'Wolf',
		baitname       = 'Bird Meat',
		enterzone = true,
		health     = 1000.0,
		timer     = 60,
	},
		{
		name       = 'huntingzone7',
		coords     = vector3(2025.0481, -1026.3876, 43.3879),
		radius     = 100.0, 
		showblip   = false,
        blipName   = 'Hunting Zone',
        blipSprite = `blip_mp_deliver_target`,
        blipScale  = 0.2,
		animal     = 'a_c_alligator_02',
		bait       = 'birdmeat',
		animalname     = 'Alligator',
		baitname       = 'Bird Meat',
		enterzone = true,
		health     = 1000.0,
		timer     = 60,
	},
}
